[info]
address = "123 Mystic Lane, Enchanted Woods, MS1 3M7, Avalon"
city = "Enchanted Woods"
country = "Avalon"
email = "merlin.archmage@arcana.com"
firstname = "Merlin"
github = "MerlinTheMage"
lastname = "Archmage"
linkedin = "merlin_magic"
middleinitial = "G"
middlename = "Gandalf"
mobile = "(+44) 777-123-4567"
postalcode = "MS1 3M7"
province = "Avalon"

[profile]
summary = "Master of Arcane Sciences with a deep understanding of magical artifacts, experienced in ancient spell crafting and proficient in alchemy. Known for rapidly mastering new spells and mystical techniques."
corecomp = [
    "quick spell learner",
    "team conjurer",
    "analytical sorcerer",
]
topqual = [
    "Aspired to become a High Mage, currently studying in the Ancient Order's Arcane Engineering program.",
    "Bachelor's degree in Arcane Sciences with over two centuries of experience in mystical development.",
    "Proactively learning new magical technologies, demonstrated by quickly mastering the creation of enchanted items and developing a popular spell with widespread acclaim.",
    "Experienced in providing arcane support for both mystical and non-mystical beings.",
    "Developed multiple magical potions with automated brewing processes and arcane ingredient sourcing.",
    "Skilled in deciphering ancient runes, exemplified by a 150x optimization in casting time during my role as a Magical Analyst.",
    "Expert at creating enchanted maps to guide decision-making and improve quest outcomes.",
]

[[qual]]
title = "Magical Expertise and Arcane Tools"
items = [
    "Spells: Fireball, Lightning Bolt, Invisibility",
    "Alchemy and Enchanting: Potion Brewing, Rune Crafting",
    "Divination: Crystal Ball, Tarot, Scrying",
    "Other: Magical History, Forbidden Tomes, Arcane Symbols",
]

[[exp]]
position = "Magical Analyst"
organization = "Council of Elders"
location = "Mystic Tower, Avalon"
datestart = "Jun 1924"
dateend = "Current"
items = [
    "Investigated and resolved inefficiencies in magical energy distribution for the Kingdom's protective barriers, discovering an ancient and forgotten ritual. Achieved a 150x power boost by optimizing spell flow, significantly enhancing defense capabilities.",
    "Led the charge in addressing the issue of misfired spells causing unintended transformations. Developed a custom charm and enchanted artifact, preventing these errors and saving the council significant resources.",
    "Spearheaded the standardization of spell casting protocols and the preservation of ancient knowledge in the Mystic Library, integrating enchanted quills for seamless documentation. This initiative improved knowledge transfer and enhanced collaboration within the Order.",
]

[[exp]]
position = "Apprentice Sorcerer"
organization = "Circle of Magi"
location = "Mystic Tower, Avalon"
datestart = "Sep 1823"
dateend = "Current"
items= [
    "Joined the Circle specifically to resolve persistent magical distortions during rituals, despite having no prior experience with high-level magic. Quickly mastered the ancient spells through dedicated practice, significantly improving ritual outcomes.",
    "Created arcane manuals and trained two additional apprentices, ensuring knowledge transfer and continuity within the Circle for consistent spellcasting.",
    "Developed a magical automation spell to manage ritual components, crucial during a high-stakes summoning. This allowed the Circle to focus on other critical tasks, ensuring the ritual's success."
]

[[project]]
name = "Enchanted Image Projection"
position = "Spell Contributor"
type = "Obsidian Plugin"
datestart = "Nov. 1923"
dateend = "Current"
items = [
    "Developed an Obsidian plugin to enable direct embedding of enchanted images in spellbooks, addressing a specific and niche demand within the magical community.",
    "Quickly learned the Obsidian API and ancient runes from scratch, successfully applying these new skills to develop a spell, despite having no prior experience.",
    "Received over 2,000 downloads and 20 bookmarks despite targeting a niche audience, reflecting its unexpected popularity and impact.",
]

[[project]]
name = "CS410 Magical Engineering Capstone"
position = "Lead Enchanter"
type = "Celestial Academy of Mystical Arts, Crystal Spire, Avalon"
datestart = "Sep 1821"
dateend = "Dec 1821"
items = [
    "Successfully led a team of four in a professional capacity to spearhead the design and development of a dynamic magical artifact using Ancient Runes and integrated Spell Templates. This project strictly followed full arcane development cycles, employing the Spiral Model.",
]

[[project]]
name = "ArcaneDocumentor"
position = "Author"
type = "Github Repo"
datestart = "Apr. 1924"
dateend = "Current"
items = [
    "Developed a tool that automates the creation of enchanted documents using ArcaneTemplates. This tool enhances efficiency by streamlining the process of creating spell scrolls with consistent formatting.",
]

[[otherexp]]
position = "Archmage's Assistant"
organization = "Applewood's Grove"
location = "Enchanted Woods, Avalon"
datestart = "June 1719"
dateend = "Current"
items = [
    "Provided consistent arcane support during apprenticeship through remote spellcasting, handling supply orders for rare ingredients, creating magical manuals, instructing on ritual operation, and managing magical records and scribe work, ensuring smooth operations even from a distance.",
    "Acquired in-depth arcane knowledge through targeted electives in Magical Flora and took the initiative to obtain a Mastery in Potion Crafting.",
    "Experimented with organic-compliant ritual designs and enchantment methods, significantly reducing ritual preparation time by half through early intervention, while aligning with sustainable magical practices.",
]

[[edu]]
degree = "Master of Arcane Sciences"
institution = "Celestial Academy of Mystical Arts"
datestart = "Sep 1718"
dateend = "Jun 1723"
location = "Crystal Spire, Avalon"
items = [
    "Excellence Scholarship Program in Arcane Sciences and Ancient Runes.",
    "Co-founder of a Sorcerer's Guild during the Arcane Plague, facilitating communication and collaboration among members.",
]
