[info]
address = "123 Mystic Lane, Enchanted Woods, MS1 3M7, Avalon"
city = "Enchanted Woods"
country = "Avalon"
email = "merlin.archmage@arcana.com"
firstname = "Merlin"
github = "MerlinTheMage"
lastname = "Archmage"
linkedin = "merlin_magic"
middleinitial = "G"
middlename = "Gandalf"
mobile = "(+44) 777-123-4567"
postalcode = "MS1 3M7"
province = "Avalon"

[profile]
summary = "Master of Arcane Sciences with a deep understanding of magical artifacts, experienced in ancient spell crafting and proficient in alchemy. Known for rapidly mastering new spells and mystical techniques."
corecomp = [
    "quick spell learner",
    "team conjurer",
    "analytical sorcerer",
]
topqual = [
    "Aspired to become a High Mage, currently studying in the Ancient Order's Arcane Engineering program.",
    "Bachelor's degree in Arcane Sciences with over two centuries of experience in mystical development.",
    "Proactively learning new magical technologies, demonstrated by quickly mastering the creation of enchanted items and developing a popular spell with widespread acclaim.",
    "Experienced in providing arcane support for both mystical and non-mystical beings.",
    "Developed multiple magical potions with automated brewing processes and arcane ingredient sourcing.",
    "Skilled in deciphering ancient runes, exemplified by a 150x optimization in casting time during my role as a Magical Analyst.",
    "Expert at creating enchanted maps to guide decision-making and improve quest outcomes.",
]

[[qual]]
title = "Magical Expertise and Arcane Tools"
items = [
    "Spells: Fireball, Lightning Bolt, Invisibility",
    "Alchemy and Enchanting: Potion Brewing, Rune Crafting",
    "Divination: Crystal Ball, Tarot, Scrying",
    "Other: Magical History, Forbidden Tomes, Arcane Symbols",
]

[[exp]]
position = "Arcane Specialist"
organization = "Elders' Council"
location = "Mystic Tower, Avalon"
datestart = "1924"
dateend = "Present"
items = [
    "Analyzed and improved magical energy systems, uncovering ancient rituals to enhance protective barriers.",
    "Addressed spell misfires and developed solutions to prevent resource wastage.",
    "Standardized spell casting protocols and preserved ancient knowledge, enhancing collaboration.",
]

[[exp]]
position = "Sorcerer Apprentice"
organization = "Magi Circle"
location = "Mystic Tower, Avalon"
datestart = "1823"
dateend = "Present"
items= [
    "Resolved magical distortions in rituals and mastered ancient spells through practice.",
    "Created manuals and trained apprentices to ensure knowledge continuity.",
    "Developed automation spells for ritual management, aiding in high-stakes summoning.",
]

[[project]]
name = "Image Projection"
position = "Contributor"
type = "Plugin"
datestart = "1923"
dateend = "Present"
items = [
    "Created a plugin for embedding images in spellbooks, meeting niche community needs.",
    "Learned new APIs and runes to develop a spell, achieving unexpected popularity.",
]

[[project]]
name = "Engineering Capstone"
position = "Lead Enchanter"
type = "Academy Project"
datestart = "1821"
dateend = "1821"
items = [
    "Led a team to design a magical artifact using runes and templates, following development cycles.",
]

[[project]]
name = "Documentor"
position = "Creator"
type = "Repository"
datestart = "1924"
dateend = "Present"
items = [
    "Created a tool for automating enchanted document creation, improving efficiency.",
]

[[otherexp]]
position = "Assistant"
organization = "Grove"
location = "Enchanted Woods, Avalon"
datestart = "1719"
dateend = "Present"
items = [
    "Provided arcane support, managed supplies, and created manuals for smooth operations.",
    "Gained knowledge in Magical Flora and achieved mastery in Potion Crafting.",
    "Experimented with ritual designs, reducing preparation time and aligning with sustainable practices.",
]

[[edu]]
degree = "Arcane Sciences"
institution = "Mystical Arts Academy"
datestart = "1718"
dateend = "1723"
location = "Crystal Spire, Avalon"
items = [
    "Participated in a scholarship program for Arcane Sciences and Runes.",
    "Co-founded a guild to facilitate member collaboration during a crisis.",
]
